### ISSUE TITLE
txpower tag not used in wlanap/digital signage device type

### ISSUE THREAD

**Issue by miguit** [opinsys/puavo#236] opened 2015-09-05 06:41 UTC
wlanap device type doesn't obey txpower tags from puavo. Txpower in devices always in full power

**Comment by tuomasjjrasanen** [comment] 2015-09-30 08:20
I need more details, this issue does not seem to be systematic. How to reproduce? What is digital signage device type??

**Comment by tuomasjjrasanen** [comment] 2015-11-11 08:15
Closed as invalid because OP did not provide any further information.

**Closed as completed by tuomasjjrasanen** 2015-11-11 08:15 UTC
Labels: 1 - Ready
