### ISSUE TITLE
Problems changing display mode with Fn+F4 combination

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#122] opened 2014-09-04 10:58 UTC
With HP Probook 430 G1 some problems occur when using external monitor or projector via hdmi or vga and changing display mode with fn+f4 (monitor) key combination. Some modes leave the laptop screen dark so that brightness is at 0%. This happens for example in clone mode with hdmi. At the same time the picture on the external device is ok.
Whit vga, fn+f4 stops working after one round toggling trough different modes. After this the external display cannot be used anymore (reboot needed) and the laptop screen goes dark. One can add brightness with fn+f10 to get some light on the screen.

When using the system app for managing screens, no problem occurs.

Tested with ltsp-opinsysrestricted-trusty-2014-08-22-095758-i386.img

**Comment by tuomasjjrasanen** [comment] 2014-09-15 13:13
Confirmed. Seems to be this: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1300914

**Comment by tuomasjjrasanen** [comment] 2014-09-16 06:24
The problem is probably somewhere in i915 driver. The error is triggered from drivers/gpu/drm/i915/intel_dp.c:564 (v3.13.0-36.63.opinsys1)

**Comment by asokero** [comment] 2016-12-29 11:51
This seems to have been fixed in the current kernels. Cannot be reproduced with HP 430 G1 using VGA or HDMI ports. Tested with image ltsp-opinsysextra-trusty-2016-12-16-134517-i386.

**Closed as completed by asokero** 2016-12-29 11:51 UTC
Labels: 4 - Done
