### ISSUE TITLE
Guest users avatar in webmenu is broken

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#77] opened 2014-06-23 07:30 UTC
Webmenu displays a broken image element for the Guest desktop session. In this case the default puavo avatar should be used instead.

**Comment by juhaerk** [comment] 2015-04-01 10:53
I have never seen this bug, and we could not reproduce it with asokero, so I am closing this one from hanging around. If it can be reproduced somehow, re-open.

**Closed as completed by juhaerk** 2015-04-01 10:53 UTC
Labels: 1 - Ready
