### ISSUE TITLE
Sound is disabled by default on some devices

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#117] opened 2014-08-28 11:15 UTC
Sound is always disabled after boot on some devices. User has to enable sound from the gnome-panel sound indicator and also add volume. Volume is at 0% before that.
This happens also with guest account.
This has been seen only on fatclients by now, but may occur on same devices when running in thin client mode (not tested).

Example machines:
Lenovo 3493ENG
*-multimedia  
       description: Audio device
       product: 6 Series/C200 Series Chipset Family High Definition Audio Controller
       vendor: Intel Corporation
       physical id: 1b
       bus info: pci@0000:00:1b.0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=snd_hda_intel latency=0
       resources: irq:45 memory:f7c00000-f7c03fff

HP Compaq 6715b
 *-multimedia  
       description: Audio device
       product: SBx00 Azalia (Intel HDA)
       vendor: Advanced Micro Devices [AMD] nee ATI
       physical id: 14.2
       bus info: pci@0000:00:14.2
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm bus_master cap_list
       configuration: driver=snd_hda_intel latency=64
       resources: irq:16 memory:84000000-84003fff

**Comment by tuomasjjrasanen** [comment] 2014-09-16 06:28
Is it reproducable with trusty images?

**Comment by tuomasjjrasanen** [comment] 2014-09-16 06:31
Tested with the same device. The problem is fixed in Trusty.

**Closed as completed by tuomasjjrasanen** 2014-09-16 06:31 UTC
