### ISSUE TITLE
Shutdown and reboot does not work on thinclient

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#139] opened 2014-09-26 12:25 UTC

**Comment by juhaerk** [comment] 2014-09-30 12:12
The title should say: Shutdown and reboot does not work on thinclient FROM THE WEBMENU.

And actually, I cannot reproduce this, which is odd, because just a week ago I complained about this problem.

Closing...

**Closed as completed by juhaerk** 2014-09-30 12:12 UTC
Labels: 2 - Working
